#!/usr/bin/env python3
"""
Generate a Synapse wall-panel Lovelace dashboard for one node, tuned for a tall phone
screen (720x1600 portrait), dark, glanceable, big touch targets. Built-in Lovelace cards
only (no HACS).

  python tools/provision/dashboard.py --node-id livingroom-01 --room "Living Room" \
      [--weather weather.home] > ha/dashboards/synapse_livingroom_01.yaml

Install: Settings -> Dashboards -> Add dashboard -> Edit -> raw config editor -> paste.
Node sensors are wired to real entity ids; house controls are clearly-marked TODO.
"""
import argparse


def slugify(s):
    out = "".join(c if c.isalnum() else "_" for c in s.lower()).strip("_")
    while "__" in out:
        out = out.replace("__", "_")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--node-id", required=True)
    ap.add_argument("--room", required=True)
    ap.add_argument("--weather", default=None)
    a = ap.parse_args()
    n = slugify(a.node_id)
    room = a.room
    S = f"sensor.synapse_{n}"
    B = f"binary_sensor.synapse_{n}"

    cards = []

    # greeting + presence (markdown with templates)
    cards.append({
        "type": "markdown",
        "content": (
            "{% set occ = is_state('" + B + "_occupancy','on') %}"
            "{% set g = ['Good night','Good morning','Good afternoon','Good evening'][now().hour // 6] %}"
            "# {{ g }}\n### " + room + " — {{ 'Occupied' if occ else 'Empty' }}"
        ),
    })

    if a.weather:
        cards.append({"type": "weather-forecast", "entity": a.weather, "show_forecast": False})

    # one-tap scenes (TODO entities)
    cards.append({
        "type": "horizontal-stack",
        "cards": [
            {"type": "button", "name": "Evening", "icon": "mdi:weather-sunset",
             "tap_action": {"action": "call-service", "service": "scene.turn_on",
                            "target": {"entity_id": "scene.evening"}}},
            {"type": "button", "name": "Movie", "icon": "mdi:movie-open",
             "tap_action": {"action": "call-service", "service": "scene.turn_on",
                            "target": {"entity_id": "scene.movie"}}},
            {"type": "button", "name": "Good night", "icon": "mdi:power-sleep",
             "tap_action": {"action": "call-service", "service": "scene.turn_on",
                            "target": {"entity_id": "scene.good_night"}}},
        ],
    })

    # room light (TODO)
    cards.append({"type": "light", "entity": "light." + slugify(room)})

    # environment glance (live node sensors)
    cards.append({
        "type": "glance", "title": room + " conditions", "columns": 3, "state_color": True,
        "entities": [
            {"entity": S + "_illuminance", "name": "Light"},
            {"entity": S + "_pressure", "name": "Pressure"},
            {"entity": S + "_wifi_rssi", "name": "Wi-Fi"},
            {"entity": B + "_occupancy", "name": "Presence"},
            {"entity": S + "_ble_known", "name": "Nearby"},
            {"entity": S + "_screen", "name": "Panel"},
        ],
    })

    # node health (live)
    cards.append({
        "type": "entities", "title": "Node health",
        "entities": [
            {"entity": B + "_online", "name": "Online"},
            {"entity": S + "_battery", "name": "Battery"},
            {"entity": B + "_charging", "name": "Charging"},
            {"entity": S + "_battery_temp", "name": "Battery temp"},
            {"entity": S + "_mem_free", "name": "Free memory"},
            {"entity": S + "_status", "name": "Status"},
        ],
    })

    dashboard = {
        "title": room,
        "views": [{
            "title": "Panel", "path": "panel", "type": "panel", "badges": [],
            "cards": [{"type": "vertical-stack", "cards": cards}],
        }],
    }

    import yaml
    header = (f"# Synapse wall panel — {room} ({a.node_id})\n"
              f"# Generated by tools/provision/dashboard.py. Node sensors are live.\n"
              f"# TODO: point scene.evening/movie/good_night and light.{slugify(room)} at your real entities.\n")
    print(header + yaml.safe_dump(dashboard, sort_keys=False, default_flow_style=False, width=100))


if __name__ == "__main__":
    main()
