#!/usr/bin/env python3
"""
Generate a Home Assistant package for one Synapse node:
  python tools/provision/ha_package.py --node-id livingroom-01 --ip 10.0.0.166 > synapse_livingroom_01.yaml
Copy the output to <HA config>/packages/ (with `homeassistant: packages: !include_dir_named packages`
in configuration.yaml) and add the printed secrets line to secrets.yaml. Then restart HA.

Gives you:
  script.synapse_<node>_say       (field: message) → speaks on the phone
  script.synapse_<node>_wake / _ambient
  binary_sensor.synapse_<node>_online (connectivity, via last_reported of the status sensor)
"""
import argparse
import json
import sys
from pathlib import Path

TEMPLATE = """\
# Synapse node {node} — generated by tools/provision/ha_package.py
rest_command:
  synapse_{slug}:
    url: "http://{ip}:8765/api/{{{{ endpoint }}}}"
    method: POST
    timeout: 8
    headers:
      X-Synapse-Key: !secret synapse_{slug}_key
    content_type: "application/json"
    payload: "{{{{ body | default('{{}}') }}}}"

script:
  synapse_{slug}_say:
    alias: "Synapse {node}: say"
    fields:
      message:
        description: Text to speak
        example: Dinner is ready
    sequence:
      - action: rest_command.synapse_{slug}
        data:
          endpoint: speak
          body: "{{{{ {{'text': message}} | tojson }}}}"
  synapse_{slug}_wake:
    alias: "Synapse {node}: wake screen"
    sequence:
      - action: rest_command.synapse_{slug}
        data: {{ endpoint: wake }}
  synapse_{slug}_ambient:
    alias: "Synapse {node}: ambient clock"
    sequence:
      - action: rest_command.synapse_{slug}
        data: {{ endpoint: ambient }}

template:
  - binary_sensor:
      - name: "Synapse {node} online"
        unique_id: synapse_{slug}_online
        device_class: connectivity
        state: >-
          {{% set s = states.sensor.synapse_{slug}_status %}}
          {{{{ s is not none and (now() - (s.last_reported | default(s.last_updated))).total_seconds() < 180 }}}}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--node-id", required=True)
    ap.add_argument("--ip", required=True)
    a = ap.parse_args()
    slug = "".join(c if c.isalnum() else "_" for c in a.node_id.lower()).strip("_")
    while "__" in slug:
        slug = slug.replace("__", "_")
    print(TEMPLATE.format(node=a.node_id, slug=slug, ip=a.ip))
    sec = Path.home() / ".synapse" / f"{a.node_id}.json"
    key = json.loads(sec.read_text())["api_key"] if sec.exists() else "<api_key from ~/.synapse/%s.json>" % a.node_id
    print(f"# secrets.yaml line (keep out of git):\n#   synapse_{slug}_key: {key}", file=sys.stderr)


if __name__ == "__main__":
    main()
